### ISSUE TITLE
Cannot compile on Java 8

### ISSUE THREAD

**Issue by alexnederlof** [alexnederlof/Jasper-report-maven-plugin#12]
Cannot compile on Java 8 because of `ClassFormatException`

```
[ERROR] [ERROR] Could not compile NoPageBreakReport.jrxml because Errors were encountered when compiling report expressions class file:
1. The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
                value = "  " + String.valueOf(((java.lang.Integer)variable_ShipCountryNumber.getValue())) + ". " + String.valueOf(((java.lang.String)field_ShipCountry.getValue())); //$JR_EXPR_ID=19$
                                                                                                                   <-------------------------------------------------------------->
1 errors

Could not compile CsvDataSourceReport.jrxml because Errors were encountered when compiling report expressions class file:
1. The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
                value = "  " + String.valueOf(((java.lang.Integer)variable_CityNumber.getValue())) + ". " + String.valueOf(((java.lang.String)field_city.getValue())); //$JR_EXPR_ID=12$
                                                                                                            <------------------------------------------------------->
1 errors

net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expressions class file:
1. The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
                value = "  " + String.valueOf(((java.lang.Integer)variable_ShipCountryNumber.getValue())) + ". " + String.valueOf(((java.lang.String)field_ShipCountry.getValue())); //$JR_EXPR_ID=19$
                                                                                                                   <-------------------------------------------------------------->
```

**Comment by guihatano** [comment]
This workaround didn't work for me

**Comment by mkielar** [comment]
I worked this around by adding this dependency to the plugin execution:

    <dependency>
        <groupId>net.sf.jasperreports</groupId>
        <artifactId>jasperreports</artifactId>
        <version>6.1.0</version>
    </dependency>

and thus replacing the `5.2.0` version specified in [plugin's `pom.xml`][1].

So now my plugin configuration looks like this:

    <plugin>
        
        <groupId>com.alexnederlof</groupId>
        <artifactId>jasperreports-plugin</artifactId>
        <version>1.6</version>
        
        <executions>
            <execution>
                <phase>process-sources</phase>
                <goals>
                    <goal>jasper</goal>
                </goals>
            </execution>
        </executions>

        <configuration>
            <compiler>net.sf.jasperreports.engine.design.JRJdtCompiler</compiler>
            <sourceDirectory>src/main/resources/reports</sourceDirectory>
            <outputDirectory>${project.build.directory}/classes/reports</outputDirectory>
            <outputFileExt>.jasper</outputFileExt>
            <xmlValidation>true</xmlValidation>
            <verbose>true</verbose>
            <numberOfThreads>2</numberOfThreads>
        </configuration>

        <dependencies>

            
            <dependency>
                <groupId>net.sf.jasperreports</groupId>
                <artifactId>jasperreports</artifactId>
                <version>6.1.0</version>
            </dependency>

            <!-- other project dependencies ->

        </dependencies>

    </plugin>


I guess the solution would be then to upgrade `net.sf.jasperreports:jasperreports` dependency to something from the `6.x.x` tree.

[1]: https://github.com/alexnederlof/Jasper-report-maven-plugin/blob/master/pom.xml#L79

**Comment by driv** [comment]
Works for me too with the workaround by mkielar

**Comment by arthurnl** [comment]
2.0 works for me to in java-8

**Comment by ardeshirayati** [comment]
Hi
I solved that by this config : [jasper](https://community.jaspersoft.com/jasperreports-library/issues/3498-0)

```
<dependency>
	<groupId>net.sf.jasperreports</groupId>
	<artifactId>jasperreports</artifactId>
	<version>5.5.1</version>
	<exclusions>
		<exclusion>
			<groupId>eclipse</groupId>
			<artifactId>jdtcore</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```
