### ISSUE TITLE
Does not support re-compilation

### ISSUE THREAD

**Issue by gorodechnyj** [alexnederlof/Jasper-report-maven-plugin#16]
When I change something in jrxml file and need to redeploy application, I do 

    $ mvn clean install

But get folowing output, among the other lines:

    [INFO] --- jasperreports-plugin:1.9:jasper (default) @ AisUiApp ---
    [INFO] Nothing to compile - all Jasper reports are up to date

**Comment by sreekanthsnair** [comment]
+1

**Comment by alexnederlof** [comment]
I don't work on this repo anymore. If you provide a PR I'm more than happy to merge it for you.

**Comment by sreekanthsnair** [comment]
Could you please give us some hint about how to achieve it then probably i can contribute it back, since i don't have any knowledge in maven plugin creation. Similarly there is one more problem ie current classpath is not getting included in jasper compilation classpath.

**Comment by panchenko** [comment]
This issue is solved by PR #11

**Comment by alexnederlof** [comment]
In that case I'm closing the issue

**Comment by gmsa** [comment]
Sorry, but I'm not finding the option to force a recompile every time. I tried looking on the diff for PR #11, but didn't find anythin related to it.
