### ISSUE TITLE
Hard Dependency on specific JasperReports Version  

### ISSUE THREAD

**Issue by uralmash** [alexnederlof/Jasper-report-maven-plugin#18]
For example If one is to use lower version of JasperReports or Higher they can not.  The fix is simple and is to make JasperReports as provided scope in plug-in pom.xml and let developers add the right JasperReports version.

**Comment by alexnederlof** [comment]
you can overwrite the plugin jasper version by excluding/setting jasper versions. Doing this dynamically would cause too many incompatibility issues.
