### ISSUE TITLE
Unable to include project's classpath

### ISSUE THREAD

**Issue by tungtran89** [alexnederlof/Jasper-report-maven-plugin#19]
It seems like unable to add the compile classpath to this plugin classpath. All the project's dependencies are not included in this plugin classpath. I tried maven-antrun-plugin to write the classpath string to a property, and then attempt to add it to the plugin's configuration, but it didn't work 
< classpathElements>
            < element>${maven.classpath}< /element>
< /classpathElements>
I'm using maven 3.1.1. jasperreports-plugin:1.6, java:1.7

**Comment by egov-systems** [comment]
+1

**Comment by thackel** [comment]
I am experiencing the same issue.
The root of the problem is that you can not choose a phase higher than "generate-resources".
At this point no classes of the project are available.
If you choose a higher phase then the plugin thinks all has been already compiled and does nothing (related to the other open recompile issue.) 

In the other ticket the author wrote that he can not work any longer on this project, so the best thing would be a fork or the usage of an other plugin.

**Comment by lucarota** [comment]
Hi all.

I use this plugin with the phase "compile" and I haven't this problem neither the recompile issue.

            <plugin>
			    <groupId>com.alexnederlof</groupId>
			    <artifactId>jasperreports-plugin</artifactId>
			    <version>1.8</version>
                <configuration>
                    <outputDirectory>${project.build.directory}/classes/reports</outputDirectory>
                    <sourceDirectory>src/main/resources/reports</sourceDirectory>
                    
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>jasper</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>net.sf.jasperreports</groupId>
                        <artifactId>jasperreports</artifactId>
                        <version>5.5.1</version>
                        <scope>runtime</scope>
                    </dependency>
                    <dependency>
                        <groupId>javax.servlet</groupId>
                        <artifactId>javax.servlet-api</artifactId>
                        <version>3.0.1</version>
                    </dependency>
                </dependencies>
			</plugin>

Cheers, 
 Luca

**Comment by tungtran89** [comment]
Dear Luca,
This help me out. Thank you! The speed of this plugin is really amazing.
