### ISSUE TITLE
Why not jasperreports-maven-plugin?

### ISSUE THREAD

**Issue by rbellamy** [alexnederlof/Jasper-report-maven-plugin#24]
Not a great question, but my obsessiveness couldn't leave it alone..

Given that you've followed the policy of releasing this with a new `groupId` and `version`, why not leave the `artifactId`?

**Comment by alexnederlof** [comment]
I don't get the question? What do you mean with a new groupId? 

I called it `jasperreports-plugin` instead of `jasperreports-maven-plugin` because `maven` is redundant here AFAIK.

**Comment by rbellamy** [comment]
https://maven.apache.org/guides/plugin/guide-java-plugin-development.html

So, why not:
```
            <groupId>com.alexnederlof</groupId>
            <artifactId>jasperreports-maven-plugin</artifactId>
            <version>2.0</version>
```

Anyway, it's a pedantic, time-wasting question... sorry for the noise.
