### ISSUE TITLE
Older versions of Jasper Reports

### ISSUE THREAD

**Issue by rbellamy** [alexnederlof/Jasper-report-maven-plugin#25]
I'm working on a large project that uses `jasperreports-3.7.0`. Needless to say, your wonderful plugin won't work for me as-is.

I toyed with the idea of refactoring to treat the properties differently, depending on which API is available (3.7 doesn't have the `DefaultJasperReportsContext`, instead using `JRProperties`) - but that's terribly messy. Multiple ClassLoaders, or wiring up the DI - all require some runtime magic. And the tests would have to be enhanced to include older versions as well.

For now, I've forked this repo and am going to deploy a `jasperreports-3.7.0` version into my private Nexus repo with a changed `groupId`. Not a great community-contributing way of dealing with it, but it'll get me moving forward.

I'd be happy to contribute something back here, if you have a suggestion that you think would work? Given the longevity of Jasper Reports, I can't imagine I'm the only one to have this need.

**Comment by rbellamy** [comment]
I see that you started this project with `jasperreports-3.7.6`.

**Comment by alexnederlof** [comment]
yes so you could also use one of the previous versions. I also couldn't figure out a clean way to make the version configurable. 

I could have gone for multiple releases like 1.0-3.x and 1.0-4.x for example, but that was too much hassle, since I'd have to maintain two versions.

**Comment by rbellamy** [comment]
That makes perfect sense. I ended up forking this repo and then publishing a modified version to my internal repository.
