### ISSUE TITLE
Configuration option to always compile all files

### ISSUE THREAD

**Issue by tobiasrdm** [alexnederlof/Jasper-report-maven-plugin#30]
Create configuration option to always compile all files. This is useful when sourceDirectory and outputDirectory are the same and the *.jrxml and *.jasper are already stored in the sources repository (SVN or Git). In that case when it is made a checkout, targetFile.lastModified() and sourceFile.lastModified() is the checkout timestamp.

The implementation can be performed using SimpleSourceInclusionScanner instead of StaleSourceScanner.

**Comment by alexnederlof** [comment]
Closed via #31

**Comment by tobiasrdm** [comment]
Released in 2.2
