### ISSUE TITLE
Why the Callable<T>? Why not the Runnable?

### ISSUE THREAD

**Issue by proweber1** [alexnederlof/Jasper-report-maven-plugin#45]
https://github.com/alexnederlof/Jasper-report-maven-plugin/blob/de807079706019693e456089a102a52c8d8ab8f0/src/main/java/com/alexnederlof/jasperreport/CompileTask.java#L77

Why you use `Callable<T>` for that task? Why not `Runnable`?

**Comment by lucarota** [comment]
Callable’s `call()` method contains `throws Exception` clause so we can propagate `JRException`.
Runnable's `run()` method signature doesn't have the throws clause.
